name: PR Closed

on:
  pull_request:
    types:
      - closed

jobs:
  pr-closed:
    name: PR Closed
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2